name: Deploy GRC Dashboard

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. BUILD NO GITHUB ACTIONS
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json: package.json
      
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --no-optional=false
      
      - name: Build Project
        run: pnpm run build

      # 2. SINCRONIZAR ARQUIVOS COM O SERVIDOR
      - name: Sync files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 89.116.191.136
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/" # Envia apenas a pasta de build
          target: "/opt/dashboard-financeiro-grc/"

      # 3. EXECUTAR O COMANDO DE REINICIALIZAÇÃO
      - name: Restart PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 89.116.191.136
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # O script agora só precisa reiniciar o PM2
            pm2 startOrRestart /opt/dashboard-financeiro-grc/dist/index.js --name dashboard-grc
